# Generated by Django 5.0.1 on 2026-02-17 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driveevent',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_drives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driveevent',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_drives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impactmetrics',
            name='donation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact_metrics', to='donations.donation'),
        ),
        migrations.AddField(
            model_name='review',
            name='acceptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='donation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='donations.donation'),
        ),
        migrations.AddField(
            model_name='review',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
