# Generated by Django 5.0.1 on 2026-02-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CLOTHES', 'Clothes'), ('TOYS', 'Toys'), ('BOOKS', 'Books')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GENTLY_USED', 'Gently Used'), ('USED', 'Used')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('preferred_pickup_start', models.DateTimeField(blank=True, null=True)),
                ('preferred_pickup_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('MATCHED', 'Matched'), ('ACCEPTED', 'Accepted'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('matching_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='donation_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'donation_images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
