# Generated by Django 5.0.1 on 2026-02-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fee_per_kg', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('commission_to_donor_pct', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('platform_fee_pct', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'waste_collectors',
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='delivery_method',
            field=models.CharField(choices=[('PLATFORM_LOGISTICS', 'Platform Logistics'), ('NGO_PICKUP', 'Custom NGO Pickup'), ('SELF_DROP', 'Self Drop-off')], default='SELF_DROP', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='logistics_provider_choice',
            field=models.CharField(blank=True, choices=[('PORTER', 'Porter'), ('RAPIDO', 'Rapido'), ('UBER', 'Uber')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='suggested_pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('MATCHED', 'Matched'), ('ACCEPTED', 'Accepted'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('WASTE_COLLECTED', 'Waste Collected')], default='CREATED', max_length=20),
        ),
    ]
