# Generated by Django 5.0.1 on 2026-02-25 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_wastecollector_donation_delivery_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='excluded_acceptors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='donation',
            name='last_rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='rejection_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('MATCHED', 'Matched'), ('RE_MATCHING', 'Re-Matching'), ('ESCALATED', 'Escalated'), ('ACCEPTED', 'Accepted'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('WASTE_REDIRECTED', 'Redirected to Recycling'), ('WASTE_COLLECTED', 'Waste Processed')], default='CREATED', max_length=20),
        ),
    ]
