# Generated by Django 5.0.1 on 2026-02-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_registration_id_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
