# Generated by Django 5.0.1 on 2026-02-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_donorprofile_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptorprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
